name: CD

run-name: >
  ${{
    github.event_name == 'push'
      && format('Production Release {0}', github.ref_name)
      || format('Deploy CI #{0}', github.event.workflow_run.run_number)
  }}

on:
  push:
    tags:
      - 'v*'

  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    if:
      ${{
          github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion == 'success'
      }}

    steps:

      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: artifact

      - name: Show artifact
        run: ls artifact/**/*.jar

      - name: Deploy
        run: |
          JAR=$(ls artifact/**/*.jar | head -n 1)
          echo "Deploying $JAR..."